### ISSUE TITLE
Bluecoat Proxy Issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shirkdog/pulledpork#154]
```
What steps will reproduce the problem?
1. Using pulledpork through a Bluecoat proxy.

What is the expected output? What do you see instead?
Download of emerging threats files and process.  Instead, I get the following 
message:

Error 500 when fetching 
https://rules.emergingthreatspro.com/open/snort-2.9.5/emerging.rules.tar.gz.md5 
at /usr/bin/pulledpork.pl line 459

Log entry related to traffic: "NULL character found in the request line from 
<IP Address>"

What version of the product are you using? On what operating system?
PulledPork v0.6.1 - Ubuntu

Please provide any additional information below.
Bluecoat KB: 
https://kb.bluecoat.com/index?page=content&id=FAQ954&cat=PRODUCTS&actp=LIST

"These kinds of messages (found NULL characters) are almost invariably caused 
by non-compliant clients of one kind or another, such as viruses, adware, 
spyware, so it is not generally traffic that should be allowed through."


```

Original issue reported on code.google.com by `travisls...@gmail.com` on 4 Apr 2014 at 12:39

**Comment by r32rtb** [comment]
I've recently run into this issue and the HTTPS request can't be passed via the HTTP::Request->new( GET as it is a protocol violation and the Bluecoats don't handle this well.  Since everything is moving to HTTPS it needs to be updated to HTTP::Request->new( CONNECT.  Please update the pulledpork.pl script to utilize the correct method for HTTPS type connections.  I've updated the script to do CONNECT method instead of GET the script works fine as long as the URLs are https.

**Comment by shirkdog** [comment]
I will do a test with the standard rule retrieval without a proxy and verify it does not affect anything.
