### ISSUE TITLE
Pulledpork issue with 'snort_dynamicrules'

### ISSUE THREAD

**Issue by robt62** [shirkdog/pulledpork#192]
I've been experiencing this issue on a recently installed snort and pulledpork installation which has been running fine (paths are correct, but shortened here):
"Loading dynamic detection library /snort_dynamicrules/file-pdf.so... ERROR: Failed to load /snort_dynamicrules/file-pdf.so: /snort_dynamicrules/file-pdf.so: ELF file OS ABI invalid"

Googling "ELF file OS ABI invalid" seems to indicate the "*.so" files have "become" 32bit on this 64bit installation.

I deleted the "*.so" files and managed to get snort working with: 'snort.conf --dump-dynamic-rules=/snort_dynamicrules'

Then I ran pulledpork, noticing that pulledpork ran 'snort.conf --dump-dynamic-rules=/tmp/....'.
When I restarted snort it then failed with the initial error again.

Do I have a misconfiguration somewhere?

**Comment by shirkdog** [comment]
Have you checked your OS setting in pulledpork.conf? This is how pulledpork will select the .so files for your architecture. 

If you delete the shared object files, but pulledpork pulls in the wrong files because, the OS setting may be the culprit.

From pulledpork.conf:

# Define your distro, this is for the precompiled shared object libs!
# Valid Distro Types:
# Debian-6-0, Ubuntu-10-4
# Ubuntu-12-04, Centos-5-4
# FC-12, FC-14, RHEL-5-5, RHEL-6-0
# FreeBSD-8-1, FreeBSD-9-0, FreeBSD-10-0
# OpenBSD-5-2, OpenBSD-5-3
# OpenSUSE-11-4, OpenSUSE-12-1
# Slackware-13-1
distro=FreeBSD-8.1

**Comment by robt62** [comment]
Thanks. I missed that setting:
I've now set 'distro=FC-12, FC-14, RHEL-5-5, RHEL-6-0'.
I also found the RHEL "*.so" files within 'so_rules' directory structure and copied them to 'snort_dynamicrules' directory.

I've restarted the snortd service and its working fine now.

Much appreciated !!!
