### ISSUE TITLE
Unknow -O option

### ISSUE THREAD

**Issue by WHK102** [shirkdog/pulledpork#211]
Run the example:

> ./pulledpork.pl -o /etc/snort/rules/ -O oinc-code -u http://www.snort.org/reg-rules/snortrules-snapshot-2973.tar.gz -i disablesid.conf -T -H

But does not works:

```
Unknown option: O

    https://github.com/shirkdog/pulledpork
      _____ ____
     `----,\    )
      `--==\\  /    PulledPork v0.7.2 - E.Coli in your water bottle!
       `--==\\/
     .-~~~~-.Y|\\_  Copyright (C) 2009-2015 JJ Cummings
  @_/        /  66\_  cummingsj@gmail.com
    |    \   \   _(")
     \   /-| ||'--'  Rules give me wings!
      \_\  \_\\

ERROR: No configuration file specified
  Usage: ...
```

**Comment by shirkdog** [comment]
This is interesting, it looks like the option is defined in the usage, but the flag for the oinkcode is not processed. Standard configuration is to put the oinkcode in your pulledpork.conf

I will take a look, but I will more than likely remove the option.

**Comment by shirkdog** [comment]
marking this as an enhancement.

**Comment by WHK102** [comment]
Thanks

**Comment by NTULINUX** [comment]
So how do we use oinkcodes if the feature is broken? If it's not a valid option or it doesn't exist in the tree, remove it from the list of possibly flags. Thanks.

**Comment by shirkdog** [comment]
Normally, the oinkcode is placed in the pulledpork.conf file for the URL you are using:

rule_url=https://www.snort.org/reg-rules/|snortrules-snapshot.tar.gz|<oinkcode>

I marked this as a bug as it is broken, but to fix it would be an enhancement.

**Comment by stan-prescott** [comment]
I also encountered this issue with the inability to pass the oinkcode to pp via the command line using version 0.7.3. I needed this ability due to automating rules downloading and processing and updating on the Linux firewall we use. If I cannot pass the oinkcode via the perl .cgi script that automates the rules download, then we must edit the pulledpork.conf file every time the automation script is run to place the oinkcode in the pulledpork.conf file. I'd like to avoid having to edit the pulledpork.conf every time if I can.

However, I was able to work around the issue by passing the VRT rules url in the format found in the config file with the oinkcode appended to the url like it is found in the config file via the command line, This seems to satisfy the need for the @base_url array variable to have the url in that format.

**Comment by tjgerot** [comment]
I believe I am encountering the same issue. I redacted the Oinkcode (which is indeed valid).

![image](https://cloud.githubusercontent.com/assets/9205510/25322003/78213e44-2878-11e7-8d17-4c870f2cea20.png)

**Comment by stan-prescott** [comment]
The -O <oinkcode> option is completely missing from the current PP script. However, if you are using the command line to execute pulledpork.pl and not the pulledpork.conf settings, there is a work-around for this. Add these arguments to the pulledpork.pl command line for the VRT rules download.

-u https://www.snort.org/reg-rules/|snortrules-snapshot.tar.gz|<your oinkcode>

**Comment by standarduserllc** [comment]
has this issue been resolved yet? I'm getting the same issue today, and when I add my oinkcode to my -u command line it doesn't work. 

I also tried adding the getopt "O=s" => /$oinkcode, on line 1644

![image](https://user-images.githubusercontent.com/22005871/31557866-c500e040-b007-11e7-8cc7-a55c00e0e348.png)

But that doesn't seem to be globally setting the variable so it can be used in the rest of the script.

Any suggestions/fixes for this issue.

Thanks.
