### ISSUE TITLE
snort[11314]: FATAL ERROR: /etc/snort/rules/snort.rules(9844) Unknown rule option: 'disable'.

### ISSUE THREAD

**Issue by romans8** [shirkdog/pulledpork#212]
Looks like after running pulled pork it seems to want to cause this error.

snort[11314]: FATAL ERROR: /etc/snort/rules/snort.rules(9844) Unknown rule option: 'disable'.

Here is whats on line 9844

alert tcp $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (msg:"ET POLICY Vulnerable Java Version 1.5.x Detected"; flow:established,to_server; content:" Java/1.5."; nocase; http_header; disable:set,ET.http.javaclient.vulnerable; threshold: type limit, count 2, seconds 300, track by_src; reference:url,javatester.org/version.html; classtype:bad-unknown; sid:2011581; rev:9;)

This is currently in my disablesid.conf as 1:2011581

Any ideas?

**Comment by shirkdog** [comment]
I need to know the specifics of your pulledpork config. The signature from emerging threats looks like this:

alert tcp $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (msg:"ET POLICY Vulnerable Java Version 1.5.x Detected"; flow:established,to_server; content:" Java/1.5."; nocase; http_header; flowbits:set,ET.http.javaclient.vulnerable; threshold: type limit, count 2, seconds 300, track by_src; reference:url,javatester.org/version.html; classtype:bad-unknown; sid:2011581; rev:9;)

So something has to be messing with the signature inside pulledpork, but because this is a default ET signature, everyone would be having the same issue with getting signature updates from Emerging Threats.

**Comment by shirkdog** [comment]
Closing this issue, as there have been some fixes to the modifysid logic which may have caused this. Reopen this issue if you notice similar behavior in the latest code.

**Comment by ClemenceR** [comment]
Hello, 
I started using PulledPork because I wanted to change the policy to security, but it seems like I have the same problem as the one above. PulledPork runs fine and generates different snort.rules according to the policy I set, but they always have the same problem. When I run Snort it quits with fatal errors, such as "Unknown rule option: 'service'", or because the "http_header" ends up after "content" - due to malformed rules in snort.rules.
PulledPork mixes the fields, sometimes even switching "," to ";" in the rules. Here are some examples of what I find in my snort.rules file vs what I extract from the online tarball given to PulledPork.

- in snort.rules:	  alert tcp $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (msg:"MALWARE-CNC Win.Trojan.Injector variant outbound connection"; flow:to_server,established; http_header; content:"User-Agent|3A| Opera|5C|9.64|0A|",fast_pattern,nocase; http_uri; content:"bb.php?v=";content:"id=",distance 0; content:"b=",distance 0; content:"tm=",distance 0; metadata:impact_flag red,policy balanced-ips drop,policy security-ips drop,ruleset community; service:http; reference:url,www.virustotal.com/en/file/2afb098dfea7d2acd73da520fe26d09acee1449c79d2c8753f3008a2a8f648b2/analysis/; classtype:trojan-activity; sid:20221; rev:7; )
- in tarball:       alert tcp $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (msg:"MALWARE-CNC Win.Trojan.Injector variant outbound connection"; flow:to_server,established; content:"User-Agent|3A| Opera|5C|9.64|0A|"; fast_pattern:only; http_header; content:"bb.php?v="; http_uri; content:"id="; distance:0; http_uri; content:"b="; distance:0; http_uri; content:"tm="; distance:0; http_uri; metadata:impact_flag red, policy balanced-ips drop, policy security-ips drop, ruleset community, service http; reference:url,www.virustotal.com/en/file/2afb098dfea7d2acd73da520fe26d09acee1449c79d2c8753f3008a2a8f648b2/analysis/; classtype:trojan-activity; sid:20221; rev:7;)

- in snort.rules:alert tcp $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (msg:"MALWARE-CNC Win.Trojan.Betad variant outbound connection"; flow:to_server,established; http_method; content:"POST"; http_uri; content:"/login.php",nocase; http_client_body; content:"|C9 97 A2 F3 7E 37 CB 7E 27|",fast_pattern,nocase; metadata:impact_flag red, policy balanced-ips drop, policy security-ips drop, ruleset community; service:http; reference:url,www.virustotal.com/en/file/46a87d0818ffd828df5c8fca63b1628f068e50cf3d20ec0e4e009e1dd547b9e9/analysis/; classtype:trojan-activity; sid:21230; rev:9; )
- in tarball:	alert tcp $HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS (msg:"MALWARE-CNC Win.Trojan.Betad variant outbound connection"; flow:to_server,established; content:"POST"; http_method; content:"/login.php"; nocase; http_uri; content:"|C9 97 A2 F3 7E 37 CB 7E 27|"; fast_pattern:only; http_client_body; metadata:impact_flag red, policy balanced-ips drop, policy security-ips drop, ruleset community, service http; reference:url,www.virustotal.com/en/file/46a87d0818ffd828df5c8fca63b1628f068e50cf3d20ec0e4e009e1dd547b9e9/analysis/; classtype:trojan-activity; sid:21230; rev:9;)

- in snort.rules:	alert tcp $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (msg:"MALWARE-CNC URI - known scanner tool muieblackcat"; flow:to_server, established; http_uri; content:"/muieblackcat",nocase; pcre:"/\/muieblackcat$/i"; metadata:policy security-ips drop,ruleset commun ity; service:http; reference:url,serverfault.com/questions/309309/what-is-muieblackcat; classtype:network-scan; sid:21257; rev:4;)
- in tarball:	alert tcp $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (msg:"MALWARE-CNC URI - known scanner tool muieblackcat"; flow:to_server, established; content:"/muieblackcat"; nocase; http_uri; pcre:"/\/muieblackcat$/Ui"; metadata:policy security-ips drop, ruleset community, service http; reference:url,serverfault.com/questions/309309/what-is-muieblackcat; classtype:network-scan; sid:21257; rev:4;)

There are at least dozens of them, as more keep coming up as I correct them. I am on Centos7, and have had the same problem when I got PulledPork from the yum repo (version 0.7.3) and from cloning the Git (version 0.7.4). I also tried to set the distro to "Centos-5-4" and precised my Snort version (2.9.13.0), still the same problem. I ran : pulledpork.pl -d -c /etc/snort/pulledpork.conf ("-d" due to problems with md5 checks)

My configuration of pulledpork.conf :
rule_url=https://www.snort.org/rules/|snortrules-snapshot-2983.tar.gz|myoinkcode
...
rule_url=https://www.snort.org/rules/|snortrules-snapshot-29130.tar.gz|myoinkcode
rule_url=https://snort.org/downloads/community/|community-rules.tar.gz|Community
rule_url=https://snort.org/downloads/community/|opensource.gz|Opensource
ignore=deleted.rules,experimental.rules,local.rules
temp_path=/tmp
rule_path=/etc/snort/rules/snort.rules
local_rules=/etc/snort/rules/local.rules
sid_msg=/etc/snort/sid-msg.map
sid_msg_version=1
sid_changelog=/var/log/sid_changes.log
sorule_path=/usr/lib64/snort_dynamicrules/
snort_path=/usr/sbin/snort
config_path=/etc/snort/snort.conf
distro=RHEL-6-0
black_list=/etc/snort/rules/iplists/default.blacklist
IPRVersion=/etc/snort/rules/iplists
snort_control=/bin/snort_control 
enablesid=/etc/snort/enablesid.conf
dropsid=/etc/snort/dropsid.conf
disablesid=/etc/snort/disablesid.conf
modifysid=/etc/snort/modifysid.conf
version=0.7.4

Maybe it's a mistake on my side but I can't see it, thanks for your help !
