### ISSUE TITLE
What is the Snort Config file?

### ISSUE THREAD

**Issue by Alex-VM** [shirkdog/pulledpork#228]
While running pulledpork.pl -c /etc/snort there I get an error saying the config file was not found. Does it mean the snort.config? Because that file is in /etc/snort... Any pointers?

**Comment by shirkdog** [comment]
pulledpork.pl comes with a configuration file (in the etc/ directory if you cloned from github called pulledpork.conf). This is the configuration file it is looking for since it needs certain flags to be set on the command line, or in the configuration file.

From the readme:
-c Where the pulledpork config file lives.

**Comment by Alex-VM** [comment]
Oh you're right. It works now, just got to update it :) Thanks a bunch

**Comment by Alex-VM** [comment]
What is the latest version, by the way? An error message shows up saying it should be the one with 0.7.2 - ALPHA, but when I go to my pulledpork.conf it shows ver 0.7.2

**Comment by shirkdog** [comment]
The ALPHA is the version added to the script to make sure the most current version is in use for testing. 0.7.2 is the current version.
