### ISSUE TITLE
Perl Modules

### ISSUE THREAD

**Issue by uihdff** [shirkdog/pulledpork#253]
Can you specify which Entware perl modules need to be downloaded to use this script ?

So for I've downloaded:

opkg install perlbase-cpan
opkg install perlbase-user
opkg install perl-www

And yet the following error occurs:

`Can't locate Crypt/SSLeay.pm in @INC (you may need to install the Crypt::SSLeay module) (@INC contains: /opt/lib/perl5/5.22 .) at ./pulledpork.pl line 28.`

**Comment by shirkdog** [comment]
On FreeBSD, it is p5-Crypt-SSLeay, on something like CentOS7 it is perl-Crypt-SSLeay

**Comment by uihdff** [comment]
@shirkdog ,

I don't see any modules with a similar name for Entware.

   [https://pkg.entware.net/binaries/armv7/Packages.html](url)

**Comment by shirkdog** [comment]
If the OS does not support it, you can try the install perl module itself from CPAN:

https://cpan.metacpan.org/authors/id/N/NA/NANIS/Crypt-SSLeay-0.72.tar.gz

Build it by hand, and take care of the dependencies. You can also setup CPAN, but I always defer to using the OS packages for support reasons, otherwise you will have to support all of your perl modules with CPAN to keep yourself sane.
